export default {
  LOGIN: 'login',
  OTP_VERIFICATION: 'otpVerfication',
  OUTER_SCREEN: 'outerScreen',
  SIGN_UP: 'signUp',
  HOME: 'home',
  OFFERS: 'offers',
  BRANDS: 'brands',
  CELEBRITY: 'celebrity',
  ACCOUNTS: 'accounts',
  TAB_ROUTES: 'tabRoutes',
  DELIVERY: 'delivery',
  RESTAURANT: 'restaurent',
  SUPERMARKET: 'supermarket',
  SUPERMARKET_PRODUCTS_CATEGORY: 'supermarketProductsCategory',
  PRODUCT_LIST: 'productList',
  DRAWER_ROUTES: 'drawerRoutes',
  QR_SCANNER: 'qrScanner',
};
